name: simonik_mahardika
description: "SIMONIK - Sistem Informasi Monitoring dan Evaluasi Indikator Kinerja untuk Institut Teknologi dan Kesehatan Mahardika"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core packages (LOCKED versions)
  firebase_core: 3.6.0
  cloud_firestore: 5.4.3
  firebase_auth: 5.3.1
  firebase_storage: 12.3.2
  
  # Google Sign In
  google_sign_in: 6.2.2
  
  # State Management
  provider: 6.1.5+1
  
  # Local Storage
  shared_preferences: 2.5.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # Charts for visualization
  fl_chart: 0.70.1
  
  # PDF Generation
  pdf: 3.11.1
  printing: 5.13.4
  
  # Image Picker for logo/kop upload
  image_picker: 1.1.2
  
  # URL Launcher for Google Drive links
  url_launcher: 6.3.1
  
  # UUID for code generation
  uuid: 4.5.1
  
  # Intl for date formatting
  intl: 0.19.0
  
  # Path Provider
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets for SIMONIK application
  assets:
    - assets/images/
    - assets/images/logo.png
    - assets/images/kop.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
